<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildThisFileDirectory)/coverage/</CoverletOutput>
    <Include>[Oxide.Core]*</Include>
    <Exclude>[xunit*]*</Exclude>
    <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
    <SingleHit>false</SingleHit>
    <UseSourceLink>true</UseSourceLink>
    <IncludeTestAssembly>false</IncludeTestAssembly>
    <ReportGeneratorReportTypes>Html;HtmlInline;HtmlInline_AzurePipelines;Cobertura</ReportGeneratorReportTypes>
    <ReportGeneratorReportContent>Full</ReportGeneratorReportContent>
    <ReportGeneratorReportStyle>ProjectView</ReportGeneratorReportStyle>
    <ReportGeneratorBaseBranch>develop</ReportGeneratorBaseBranch>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Oxide.References" Version="2.0.3799-testing" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReportGenerator" Version="5.2.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Oxide.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logging\" />
    <Folder Include="Configuration\" />
    <Folder Include="Database\" />
    <Folder Include="ServerConsole\" />
    <Folder Include="RemoteConsole\" />
    <Folder Include="Pooling\" />
  </ItemGroup>

</Project>
